import { Geist, Geist_Mono, Rowdies } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rowdies = Rowdies({
  weight: ['300', '400', '700'],
  subsets: ["latin"]
})

export const metadata = {
  title: "Programming School",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rowdies} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
